### ISSUE TITLE
VPN CLI reference doesn't render properly on Chrome

### ISSUE THREAD

**Issue by nathan-hekman** [ibm-cloud-docs/vpc-infrastructure-cli-plugin#3] opened 2021-02-24 18:22 UTC
Try going directly here: https://cloud.ibm.com/docs/cli?topic=vpc-infrastructure-cli-plugin-vpc-reference#vpn-clis or down a bit here: https://cloud.ibm.com/docs/cli?topic=vpc-infrastructure-cli-plugin-vpc-reference

The page doesn't render properly for me on Chrome, macOS

![image](https://user-images.githubusercontent.com/6822736/109046989-f86f0a80-769a-11eb-9061-2160dec8f043.png)

**Comment by sheltons** [comment] 2021-03-03 15:39
Checked source, cannot reproduce. 
Closing.

**Closed by sheltons** 2021-03-03 15:39 UTC
